---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: vagrant-ubuntu-12.04
    box_url: http://files.vagrantup.com/precise64.box
    require_chef_omnibus: true
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: vagrant-ubuntu-10.04
    box_url: http://files.vagrantup.com/lucid64.box
    require_chef_omnibus: true
  run_list:
  - recipe[apt]
#- name: centos-6.3
#  driver_config:
#    box: opscode-centos-6.3
#    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box
#  run_list:
#  - recipe[yum]
#- name: centos-5.8
#  driver_config:
#    box: opscode-centos-5.8
#    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.8_chef-11.2.0.box
#  run_list:
#  - recipe[yum]

suites:
- name: lsyncd-default
  run_list:
  - recipe[build-essential]
  - recipe[supervisor]
  - recipe[lsyncd]
  attributes: {}
- name: lsyncd-2.0.7
  run_list:
  - recipe[build-essential]
  - recipe[supervisor]
  - recipe[lsyncd]
  attributes:
    lsyncd:
      src:
        revision: "release-2.0.7"
- name: lsyncd-2.1.4
  run_list:
  - recipe[build-essential]
  - recipe[supervisor]
  - recipe[lsyncd]
  attributes:
    lsyncd:
      src:
        revision: "release-2.1.4"
